name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env: 
      PYTHONPATH: ${{ github.workspace }}
    steps:

      - name: Checkout Repository 
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Ls
        run: ls -R

      - name: Install dependencies 
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 --exclude venv, test/__pycache__