# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint and Test Python Code
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
      
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies inside virtual environment
      run: |
        python -m venv venv
        venv/bin/pip install --upgrade pip
        venv/bin/pip install flake8 pytest
        if [ -f requirements.txt ]; then venv/bin/pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        venv/bin/flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        venv/bin/flake8 . --exclude=venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with pytest
      run: |
        venv/bin/pytest
